### ISSUE TITLE
GrandAvg issue (update: really a BINOPER > ERP2IPSICONTRA issue)

### ISSUE THREAD

**Issue by jasonarita** [lucklab/erplab#15]
From Chris Loersch: 

I am working on trying to get a grand average made for some a lateralized component and have run into a problem.  I made averages for each individual subject using the contra-ipsi assistant and can't seem to find a way to get ERPLab to create a grand average from these files.  

Despite every file looking identical (made using a scripted loop; confirmed by looking at the ERP structure upon loading the files), I get the following error whenever I try to use the grand average tool to combine these files:

![unnamed](https://cloud.githubusercontent.com/assets/5808953/5882221/53ed1c04-a2fc-11e4-92e7-a21fdf1c4d4b.png)

**Comment by Percpt** [comment]
This looks like an issue w/ BINOPER function since Chris' example ERP-files seem to be malformed. The number of bins in the ERP structure (ERP.NBINS) didn't match the number of bins in the ERP.NTRIALS structure (ERP.NTRIALS.ACCEPTED, ERP.NTRIALS.REJECTED, ERP.NTRIALS.INVALID, ERP.NTRIALS.ARFLAGS)

  ERP.BINS = 16;
  while
  ERP.NTRIALS.ACCEPTED = 1x41 bin array

I'm updating BINOPER so that it updatas the ERP.NTRIALS structure.

**Comment by Percpt** [comment]
Need to update the following fields:
- ERP.ntrials.accepted  (sum the input bins) 
- ERP.ntrials.rejected
- ERP.ntrials.invalid
- ERP.ntrials.arflags  (use bitwiseOR on input bins)

use BINPOS variable to access the input bin
