### ISSUE TITLE
Error: JFADELETTIMESEGMENTS

### ISSUE THREAD

**Issue by jasonarita** [lucklab/erplab#21]
----
#### From Jaclyn Farrens
 subjects **45, 54, 70 and 94** the ignoreEventCodes function in the ICA_prep_P9P10 script doesn't work (line 33).
```
durationThreshold   = 2000;     % Remove data-segments in which event codes are greater than 2000 ms apart
eventCodeBufferMS   = 1000;      % Preserve data-segments 1000ms before and after stim-event codes 
ignoreEventCodes   = [setdiff(unique([inputEEG.event.type]), [70 80])]; %Get's list of all undesired event codes to pass to ignoreEventCodes
EEGbreaksRemoved    = JFAdeleteTimeSegment(inputEEG, durationThreshold, eventCodeBufferMS, eventCodeBufferMS, ignoreEventCodes);

```
 It doesn't recognize the stream of eventcodes as eventcodes so it doesn't properly remove the extra time at the begining and ends of the files or the stream of standards at the beginning even though there is nothing noticeably different about these four subjects. Its the same task, same computer, same processing scripts, etc. I have included subject 85 as an example of how the function should work. You can ignore the second half of the ICA_prep script, that part works fine.

**Comment by percpt** [comment]
Problem
=====
The error occurs in the case where the subject data has only one time window to reject. 

According to the code:
```
if rejectionWindowCount==1
        fprintf('\nNote: No large segment was found.\n')
else
        rejectionWindows = ERPLAB403joinclosesegments(rejectionWindows, [], 5);
```
For some reason if there exists a single valid time-window to reject, JFADELETETIMESEGMENTS does not reject that window because of the check ```if rejectionWindowCount==1'```. Even if this is changed to ```if rejectionWindowCount<1``` we need to also change the function call to JOINCLESESEGMENTS, since when that function is given a single rejection window then it returns

Solution
=====

```
if rejectionWindowCount<1
        fprintf('\nNote: No large segment was found.\n')
else
        if(rejectionWindowCount>1)
              rejectionWindows = ERPLAB403joinclosesegments(rejectionWindows, [], 5);
        end
```
