### ISSUE TITLE
ERP Measurement tool GUI cutting off

### ISSUE THREAD

**Issue by mcweenysean** [lucklab/erplab#68]
Hi,

I have run into a problem in which the ERP Measurement Tool GUI cuts off the top part of my GUI so that I am unable to select mean amplitude between two frequencies. This is one of two GUIs that this happens to with the other being the epoch4avgGUI under the weighted averager GUI. I tried changing my screen resolution from 1280x800 (best) to no avail. Are there any solutions? Attached is what my GUI looks like
![screen shot 2017-07-12 at 7 29 24 pm](https://user-images.githubusercontent.com/30132655/28145647-7f995328-6739-11e7-8a12-98673af34d27.png)

|----| ---- | 
| OS version     | [*OSX 10.10.5*] |
| Matlab version | [*2016b*] |
| EEGLAB version | [*14.0.0*] |
| ERPLAB version | [*6.1.3*] |

**Comment by andrewxstewart** [comment]
Hi there,

This has been recently fixed, but the fix is not yet in a full release version.

Get the latest commit, which contains the ERP Measurement Tool GUI fix, here:
https://github.com/lucklab/erplab/archive/master.zip

There are some more details here:
https://github.com/lucklab/erplab/issues/63

**Comment by mcweenysean** [comment]
That worked - thanks so much!
