### ISSUE TITLE
Binlister assignation error

### ISSUE THREAD

**Issue by cmmoenne** [lucklab/erplab#85]
### Binlister Error
We have the following binlister:

```
bin 1

correct

.{1;2}{31;41}


bin 2

incorrect

.{1;2}{32;42}
```
and the following bin assignation (only an excerpt):

```

# item	 bepoch	  ecode	            label	      onset	          diff	     dura	b_flags	   a_flags	  enable	    bin
#                                                 (sec)           (msec)     (msec)    (binary)   (binary)


1     	0     	      2	              ""	      1.3633	      0.00	    0.0	    00000000     00000000	   1	[   1  2]
2     	0     	     13	              ""	      2.0942	    730.96	    0.0	    00000000     00000000	   0	[       ]
3     	0     	     41	              ""	      2.9136	    819.34	    0.0	    00000000     00000000	   1	[       ]
4     	0     	     21	              ""	      4.4688	   1555.18	    0.0	    00000000     00000000	   1	[       ]
5     	0     	      1	              ""	      5.1709	    702.15	    0.0	    00000000     00000000	   1	[   1  2]
6     	0     	     13	              ""	      5.8237	    652.83	    0.0	    00000000     00000000	   0	[       ]
7     	0     	     31	              ""	      6.6431	    819.34	    0.0	    00000000     00000000	   1	[       ]
8     	0     	     22	              ""	      8.3657	   1722.66	    0.0	    00000000     00000000	   1	[       ]
9     	0     	      2	              ""	      9.1626	    796.88	    0.0	    00000000     00000000	   1	[   1  2]
10    	0     	     13	              ""	      9.6538	    491.21	    0.0	    00000000     00000000	   0	[       ]
11    	0     	     41	              ""	     10.4731	    819.34	    0.0	    00000000     00000000	   1	[       ]
12    	0     	     22	              ""	     12.2124	   1739.26	    0.0	    00000000     00000000	   1	[       ]
13    	0     	      2	              ""	     12.9707	    758.30	    0.0	    00000000     00000000	   1	[   1  2]
14    	0     	     13	              ""	     13.4668	    496.09	    0.0	    00000000     00000000	   0	[       ]
15    	0     	     41	              ""	     14.2866	    819.82	    0.0	    00000000     00000000	   1	[       ]
16    	0     	     11	              ""	     15.8418	   1555.18	    0.0	    00000000     00000000	   1	[       ]
17    	0     	      1	              ""	     16.6265	    784.67	    0.0	    00000000     00000000	   1	[   1  2]
18    	0     	     13	              ""	     17.0459	    419.43	    0.0	    00000000     00000000	   0	[       ]
19    	0     	     31	              ""	     17.8657	    819.82	    0.0	    00000000     00000000	   1	[       ]
20    	0     	     21	              ""	     19.7388	   1873.05	    0.0	    00000000     00000000	   1	[       ]
21    	0     	      1	              ""	     20.6665	    927.73	    0.0	    00000000     00000000	   1	[   1  2]
22    	0     	     13	              ""	     20.8926	    226.07	    0.0	    00000000     00000000	   0	[       ]
23    	0     	     31	              ""	     21.7124	    819.82	    0.0	    00000000     00000000	   1	[       ]
24    	0     	     21	              ""	     23.5688	   1856.45	    0.0	    00000000     00000000	   1	[       ]
25    	0     	      1	              ""	     24.3701	    801.27	    0.0	    00000000     00000000	   1	[   1  2]
26    	0     	     13	              ""	     24.6724	    302.25	    0.0	    00000000     00000000	   0	[       ]
27    	0     	     31	              ""	     25.4922	    819.82	    0.0	    00000000     00000000	   1	[       ]
28    	0     	     22	              ""	     27.1143	   1622.07	    0.0	    00000000     00000000	   1	[       ]
29    	0     	      2	              ""	     27.7861	    671.88	    0.0	    00000000     00000000	   1	[   1  2]
30    	0     	     13	              ""	     28.1514	    365.23	    0.0	    00000000     00000000	   0	[       ]
31    	0     	     41	              ""	     28.9707	    819.34	    0.0	    00000000     00000000	   1	[       ]
```
We use the following ERPLab command:

```
% binlister
EEG  = pop_binlister(EEG, 'BDF', BINLIST, 'IndexEL', 1,'ExportEL', [wkdir_blogs '/bin_' set_name '.txt'], 'Ignore', [13]);
```

#### Expected behavior:
As far as we understand, the assignation is incorrect, because 2->41 = _bin 1_, but not _bin 2_.

#### Versions
Mac / Matlab 2018a /  EEGLab 14.1.1b / ERPLab 7.0.0

**Comment by andrewxstewart** [comment]
Weird.

So the problem is that some items are being written to both bin 1 and bin 2, when you desire these items to be in only one?

My read of the Bin-Descriptor that you listed there is:
Bin 1 - correct - only when a {1 or 2} is immediately followed by a {31 or 41}, and 
Bin 2 - incorrect - only when a {1 or 2} is immediately followed by a {32 or 42}

is that what you are aiming for?

If so, I agree that these should be mutually exclusive.

Have you run binlister only a single time on each dataset?

For bughunting, maybe we should try dropping that 'ignore 13', and, on a clean dataset, try a BDF of:

```
bin 1
correct
.{1;2}{13}{31;41}

bin 2
incorrect
.{1;2}{13}{32;42}
```

Note that there is a single new line after each bit, with empty lines only between bin descriptor items.

**Comment by cmmoenne** [comment]
Yes, that is what we expect (mutually exclusive bins).

Without the ignore option everything seems to work well (as far as I can see). Sadly, we can not use the binlister with {13}, because trigger 13 can appear before/after triggers 1 and 2. I think that if we use 4 bins we can solve our issue through bin operations:
```
bin 1
correct 1
.{1;2}{13}{31;41}

bin 2
incorrect 1
.{1;2}{13}{32;42}

bin 1
correct 2
{13}.{1;2}{31;41}

bin 2
incorrect 2
{13}.{1;2}{32;42}
```
It seems that the ignore option is not working properly :'-(

**Comment by andrewxstewart** [comment]
Ok - I'm glad this works well for you now.

You could combine these bins after in the ERP Bin Operations tool.

Another option would be to specify .{1;2} then a response code not necessarily immediately after, but within a specific time range in ms. So for 0.1 to 2 seconds:

```
bin 1
correct
.{1;2}{t<100-2000>31;41}

bin 2
incorrect
.{1;2}{t<100-2000>32;42}
```
https://github.com/lucklab/erplab/wiki/BDF-Library

**Comment by cmmoenne** [comment]
Thank you for your help @andrewxstewart

**Comment by stephaarmstrong** [comment]
Hi. this question string was very useful to solve a similar problem. However, I still cannot find how to assign a bin for all my events. In my case, I have created  a "conditional" bin. Below an example (auditory and visual blocks have 7 bins each, this is just an example)

bin 1
auditory block standard
.{1}
bin 2
auditory block deviant min40
{1}.{21}{1}

bin 8
visual block standard
.{2}
bin 9
visual block deviant min40
{2}.{21}{2}

My problem is that the deviant events (21 and 22) are not always preceded or followed by a standard, since some blocks start or finish with a deviant, or two deviants are displayed sequentially . So, in this cases they are not recognised within any bin, like in the example below:

131 | 0 | 1 | S1 | 178.682 | 1544.01 | 2 | 00000000     00000000 | 1 | [        1]
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
132 | 0 | 22 | S22 | 180.324 | 1642 | 2 | 00000000     00000000 | 1 | [       ]
133 | 0 | 22 | S22 | 181.724 | 1399.99 | 2 | 00000000     00000000 | 1 | [       ]
134 | 0 | 1 | S1 | 183.108 | 1384 | 2 | 00000000     00000000 | 1 | [      1]
135 | 0 | 1 | S1 | 184.674 | 1565.99 | 2 | 00000000     00000000 | 1 | [      1]
136 | 0 | 1 | S1 | 186.274 | 1600.01 | 2 | 00000000     00000000 | 1 | [      1]
137 | 0 | 1 | S1 | 187.908 | 1634 | 2 | 00000000     00000000 | 1 | [      1]
138 | 0 | 22 | S22 | 189.408 | 1500 | 2 | 00000000     00000000 | 1 | [      3]
139 | 0 | 1 | S1 | 190.974 | 1565.99 | 2 | 00000000     00000000 | 1 | [      1]
140 | 0 | 1 | S1 | 192.518 | 1544.01 | 2 | 00000000     00000000 | 1 | [      1]

So, how can I fix this?
